project:
  type: website
  output-dir: C:\Users\hswearin.stu\OneDrive - UBC\Documents\UBC\e-portfolio\E-Portfolio

website:
  title: "Hannah Swearingen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: publications.qmd
        text: Publications
      - href: content.qmd
        text: Content & Deliverables

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

